"""remove_user_agent

Revision ID: 48286733428d
Revises: 9684d676ed69
Create Date: 2025-05-22 10:42:56.295340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '48286733428d'
down_revision: Union[str, None] = '9684d676ed69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_meta_data', 'user_agent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_meta_data', sa.Column('user_agent', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
