"""add_config

Revision ID: 9684d676ed69
Revises: 08eb6dfcd15c
Create Date: 2025-05-22 10:12:41.277203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9684d676ed69'
down_revision: Union[str, None] = '08eb6dfcd15c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscription_settings', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('support_email', sqlmodel.sql.sqltypes.AutoString(), ),
    sa.Column('support_phone', sqlmodel.sql.sqltypes.AutoString(), ),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configs')
    # ### end Alembic commands ###
