"""auth.status

Revision ID: 01ea93b8c443
Revises: 8d8bb9cbde42
Create Date: 2025-05-22 17:41:04.395075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '01ea93b8c443'
down_revision: Union[str, None] = '8d8bb9cbde42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth', sa.Column('status', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth', 'status')
    # ### end Alembic commands ###
