"""model_fix

Revision ID: 08eb6dfcd15c
Revises: 758bbbbaa55a
Create Date: 2025-05-22 08:16:48.588656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08eb6dfcd15c'
down_revision: Union[str, None] = '758bbbbaa55a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_config', sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True))
    op.drop_column('app_config', 'update_at')
    op.add_column('app_modules', sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True))
    op.drop_column('app_modules', 'update_at')
    op.add_column('assets', sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True))
    op.drop_column('assets', 'update_at')
    op.add_column('business_preferences', sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True))
    op.drop_column('business_preferences', 'update_at')
    op.add_column('businesses', sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True))
    op.drop_column('businesses', 'update_at')
    op.add_column('customers', sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True))
    op.drop_column('customers', 'update_at')
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True))
    op.drop_column('users', 'update_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('users', 'updated_at')
    op.add_column('customers', sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('customers', 'updated_at')
    op.add_column('businesses', sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('businesses', 'updated_at')
    op.add_column('business_preferences', sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('business_preferences', 'updated_at')
    op.add_column('assets', sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('assets', 'updated_at')
    op.add_column('app_modules', sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('app_modules', 'updated_at')
    op.add_column('app_config', sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('app_config', 'updated_at')
    # ### end Alembic commands ###
