"""initiator_creator

Revision ID: 1a6735905d33
Revises: 01ea93b8c443
Create Date: 2025-05-29 18:02:10.941589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1a6735905d33'
down_revision: Union[str, None] = '01ea93b8c443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('creator_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'customers', 'users', ['creator_id'], ['uid'])
    op.add_column('transactions', sa.Column('initiator_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'users', ['initiator_id'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'initiator_id')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'creator_id')
    # ### end Alembic commands ###
