"""sms_alert

Revision ID: 474187800729
Revises: 50917a50db5a
Create Date: 2025-06-26 09:56:34.628378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '474187800729'
down_revision: Union[str, None] = '50917a50db5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('sms_alert', sa.VARCHAR(), server_default='YES', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'sms_alert')
    # ### end Alembic commands ###
