"""customer-code

Revision ID: 50917a50db5a
Revises: 171836d76d3e
Create Date: 2025-06-24 10:52:08.020470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '50917a50db5a'
down_revision: Union[str, None] = '171836d76d3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('customer_type', sa.VARCHAR(), nullable=True))
    op.add_column('customers', sa.Column('customer_code', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'customer_code')
    op.drop_column('customers', 'customer_type')
    # ### end Alembic commands ###
