"""updated_by

Revision ID: 6eff8cfd678f
Revises: 1a6735905d33
Create Date: 2025-05-29 19:32:07.186568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6eff8cfd678f'
down_revision: Union[str, None] = '1a6735905d33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('updated_by_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'users', ['updated_by_id'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'updated_by_id')
    # ### end Alembic commands ###
