"""user_business_id

Revision ID: 868052adc49d
Revises: 48286733428d
Create Date: 2025-05-22 11:37:11.773438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '868052adc49d'
down_revision: Union[str, None] = '48286733428d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'business_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Uuid(),
               existing_nullable=True)
    op.create_foreign_key(None, 'users', 'businesses', ['business_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'business_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
