"""customer_name

Revision ID: ab7e1cb47af0
Revises: 474187800729
Create Date: 2025-07-01 08:49:46.788219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ab7e1cb47af0'
down_revision: Union[str, None] = '474187800729'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('name', sa.VARCHAR(), nullable=True))
    op.drop_column('customers', 'last_name')
    op.drop_column('customers', 'first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('customers', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('customers', 'name')
    # ### end Alembic commands ###
